### ISSUE TITLE
webui调取出错

### ISSUE THREAD

**Issue by softbeast** [v3ucn/Bert-vits2-V2.3#2]
您好啊，我用你的notebook训练自己的一个声音，跑到最后webui的时候报这个错，是需要修改哪里的配置文件么？谢谢

| numexpr.utils | INFO | NumExpr defaulting to 2 threads.
/usr/local/lib/python3.10/dist-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Traceback (most recent call last):
  File "/content/Bert-vits2-V2.3.1/webui.py", line 380, in <module>
    net_g = get_net_g(
  File "/content/Bert-vits2-V2.3.1/infer.py", line 98, in get_net_g
    _ = utils.load_checkpoint(model_path, net_g, None, skip_optimizer=True)
  File "/content/Bert-vits2-V2.3.1/utils.py", line 66, in load_checkpoint
    assert os.path.isfile(checkpoint_path)
AssertionError

**Comment by softbeast** [comment]
找到了。模型名称改一下就ok了。
